nome= input('digite o nome da aluna:')
idade= int(input('digite a idade da aluna:'))
altura= float(input('digite a altura da aluna:'))
hobbies= input('digite os hobbies da aluna seperado por vírgula')
hobbies1= hobbies.split(',')
endereco_rua = input('digite o nome da rua da aluna:')
endereco_numero = int(input('digite o numero da casa da aluna:'))               
endereco_cidade = input('digite o nome da cidade da aluna:')
endereco = (endereco_rua, endereco_numero, endereco_cidade) #crie uma tupla
email = input('digite o email da aluna:')
telefone = input('digite o telefone da aluna:')
contato = {'email': email, 'telefone': telefone, } #crie um dicionário
print('olá, segue informação sobre a aluna:')
print('Nome:', nome)
print('Idade:', idade)
print('Altura:', altura)
print('Hobbies:', hobbies1)
print('Endereco:', endereco)
print('Contato:', contato)
